version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py

python:
  install:
    - method: pip
      command: python -m ensurepip
    - method: pip
      path: .
      extra_requirements: ['pip']
    - method: pip
      path: .
    - requirements: requirements.txt